annslogs/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('annslogsapp.urls', namespace='annslogsapp')),
    path('', include('annsusers.urls', namespace='annsusers')),

]

annslogsapp/urls.py
"""annslogsapp URL Configuration
这里定义app的URL模式
"""
from django.urls import path
from annslogsapp import views

app_name = 'annslogsapp'
urlpatterns = [
    # 主页
    path('', views.index, name='index'),
    #Topic
    path('topics/', views.topics, name='topics'),
    #Topic的细节
    path('topic/<topic_id>/',  views.topic, name='topic'),

    # 用于添加新主题的网页
    path('new_topic/', views.new_topic, name='new_topic'),

    # 用于添加主题新条目的网页
    path('new_entry/<topic_id>/', views.new_entry, name='new_entry'),
    # 用于主题条目编辑的网页
    path('edit_entry/<entry_id>/', views.edit_entry, name='edit_entry'),
]

annsusers/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView
from . import views

app_name = 'annsusers'

urlpatterns = [
    #登录界面  LoginView.as_view后面要加上()
    path('login/', LoginView.as_view(template_name='annsusers/login.html'), name='login'),
    # 注销
    path('logout/', views.logout_view, name='logout'),
    # 注册页面
    path('register/', views.register, name='register'),
]

annslogsapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Topic(models.Model):
    name = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class Entry(models.Model):
    topic = models.ForeignKey('Topic', on_delete=models.CASCADE)
    name = models.TextField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        if len(self.name) > 50:
            return self.name[:50] + "..."
        else:
            return self.name

annsusers/models.py
from django.db import models

# Create your models here.

annslogsapp/forms.py
#!/usr/bin/python
# -*- coding:utf-8 -*-
#@Author : jiaoxiao.lan
#@File   : forms.py

from django import forms
from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['name',]
        # 让 Django 不要为字段 name 生成标签
        labels = {'name': ''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['name']
        labels = {'name': ''}
        # 设置属性widgets，可覆盖Django选择的默认小部件
        # 文本区域改成80列（非默认的40列）
        widgets = {'name': forms.Textarea(attrs={'cols': 80})}

annslogsapp/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from .models import Topic
from .forms import TopicForm, EntryForm, Entry

# Create your views here.
def index(request):
    return render(request, 'annslogsapp/index.html')


""" 将login_required()作为装饰器 """
# 在访问topics（）之前要先调用login_required()
@login_required()
def topics(request):

    # 仅显示主题名称
    topics = Topic.objects.order_by('date_added')
    context = {'topics': topics}
    return render(request, 'annslogsapp/topics.html', context)


""" 显示单个主题及其所有条目 """
@login_required()
def topic(request, topic_id):
    topic = Topic.objects.get(id=topic_id)

    check_topic_owner(topic, request)

    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'annslogsapp/topic.html', context)


"""创建新主题"""
@login_required()
def new_topic(request):
    # 添加新主题
    if request.method != 'POST':
        form = TopicForm()
    else:
        # 对POST提交的数据进行处理
        form = TopicForm(request.POST)
        if form.is_valid():
            # 将新建的主题关联到当前登录的账号
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return HttpResponseRedirect(reverse('annslogsapp:topics'))
    context = {'form': form}
    return render(request, 'annslogsapp/new_topic.html', context)


""" 在子主题下添加内容 """
@login_required()
def new_entry(request, topic_id):

    topic = Topic.objects.get(id=topic_id)

    check_topic_owner(topic, request)

    if request.method != 'POST':
        # 未提交数据 , 创建一个空表单
        form = EntryForm()
    else:
        # POST 提交的数据 , 对数据进行处理
        form = EntryForm(data=request.POST)
        if form.is_valid():
            # 传递了实参commit=False，让Django创建一个新的配料对象，并将其存储到new_topping中，但不将它保存到数据库中
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            # 把配料保存到数据库，并将其与正确的披萨相关联
            new_entry.save()
            return HttpResponseRedirect(reverse('annslogsapp:topic', args=[topic_id]))
    context = {'topic': topic, 'form': form}
    return render(request, 'annslogsapp/new_entry.html', context)


""" 编辑既有条目 """
@login_required()
def edit_entry(request, entry_id):
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic

    check_topic_owner(topic, request)

    if request.method != 'POST':
        # 初次请求，使用当前条目填充表单
        form = EntryForm(instance=entry)
    else:
        # POST 提交的数据，对数据进行处理
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('annslogsapp:topic', args=[topic.id]))
    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'annslogsapp/edit_entry.html', context)

def check_topic_owner(topic, request):
    """校验关联到的用户是否为当前登录的用户"""
    if topic.owner != request.user:
        raise Http404

annsusers/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm

# Create your views here.

""" 注销用户 """
def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('annslogsapp:index'))


""" 注册新用户 """
def register(request):
    if request.method != 'POST':
        # 显示空的注册表单
        form = UserCreationForm()
    else:
        # 处理填写好的表单
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            # 让用户自动登录，再重定向到主页
            authenticated_user = authenticate(username=new_user.username, password=request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('annslogsapp:index'))
    context = {'form': form}
    return render(request, 'annsusers/register.html', context)

annslogsapp/templates/annslogsapp/base.html
{% load bootstrap3 %}

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
        "http://www.w3.org/TR/html4/loose.dtd">

<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Learning Log</title>
        {% bootstrap_css %}
        {% bootstrap_javascript %}
    </head>
<body>
<!-- Static navbar -->
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
        <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed"
            data-toggle="collapse" data-target="#navbar"
            aria-expanded="false" aria-controls="navbar">
        </button>
        <a class="navbar-brand" href="{% url 'annslogsapp:index' %}">
            Learning Log</a>
        </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'annslogsapp:topics' %}">Topics</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                    <li><a>Hello, {{ user.username }}.</a></li>
                    <li><a href="{% url 'annsusers:logout' %}">Log out</a></li>
                    {% else %}
                    <li><a href="{% url 'annsusers:register' %}">Register</a></li>
                    <li><a href="{% url 'annsusers:login' %}">Log in</a></li>
                    {% endif %}
                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </nav>
</nav>
<div class="container">
<div class="page-header">
    {% block header %}{% endblock header %}
</div>
<div>
    {% block content %}{% endblock content %}
</div>
</div> <!-- /container -->
</body>
</html>

annslogsapp/templates/annslogsapp/edit_entry.html
{% extends "annslogsapp/base.html" %}
{% block content %}
<p>
    <a href="{% url 'annslogsapp:topic' topic.id %}">{{ topic }}</a>
</p>
<p>Edit entry:</p>
    <form action="{% url 'annslogsapp:edit_entry' entry.id %}" method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">Save changes</button>
    </form>
{% endblock content %}

annslogsapp/templates/annslogsapp/index.html
{% extends "annslogsapp/base.html" %}
{% block header %}
<div class='jumbotron'>
    <h1>Track your learning.</h1>
</div>
{% endblock header %}
{% block content %}
<h2>
    <a href="{% url 'annsusers:register' %}">Register an account</a> to make
    your own Learning Log, and list the topics you're learning about.
</h2>
<h2>
    Whenever you learn something new about a topic, make an entry
    summarizing what you've learned.
</h2>
{% endblock content %}

annslogsapp/templates/annslogsapp/new_entry.html
{% extends "annslogsapp/base.html" %}
{% block content %}
<p>
    <a href="{% url 'annslogsapp:topic' topic.id %}">{{ topic }}</a>
</p>
<p>Add a new entry:</p>
<form action="{% url 'annslogsapp:new_entry' topic.id %}" method='post'>
{% csrf_token %}
{{ form.as_p }}
<button name='submit'>Add entry</button>
</form>
{% endblock content %}

annslogsapp/templates/annslogsapp/new_topic.html
{% extends "annslogsapp/base.html" %}
{% block content %}
    <p>Add a new topic:</p>
    <form action="{% url 'annslogsapp:new_topic' %}" method='post'>
        <!-- 防止攻击者利用表单来获得对服务器未经授权的访问 -->
        {% csrf_token %}
        <!-- 显示表单（段落格式渲染） -->
        {{ form.as_p }}
        <button name="submit">Add Topic</button>
    </form>
{% endblock content %}

annslogsapp/templates/annslogsapp/topic.html
{% extends "annslogsapp/base.html" %}
{% block content %}
    <p>Topics: {{topic}}</p>
    <p>Entries:</p>
     <p>
         <a href="{% url 'annslogsapp:new_entry' topic.id %}">New entry</a>
     </p>
        <ul>
            {% for entry in entries %}
            <li>
                <p>{{ entry.date_added|date:'M d, Y H:i' }}</p>
                <p>{{ entry.name|linebreaks }}</p>
                <p>
                    <a href="{% url 'annslogsapp:edit_entry' entry.id %}">Edit entry</a>
                </p>
            </li>
            {% empty %}
            <li>No entries have been added yet.</li>
            {% endfor %}
        </ul>
{% endblock content %}

annslogsapp/templates/annslogsapp/topics.html
{% extends "annslogsapp/base.html" %}
{% block content %}
<p>Topics</p>
<ul>
    {% for topic in topics %}
    <li>
        <a href="{% url 'annslogsapp:topic' topic.id %}">{{ topic }}</a>
    </li>
    {% empty %}
    <li>No topics have been added yet.</li>
    {% endfor %}
</ul>
<a href="{% url 'annslogsapp:new_topic' %}">Add a new topic:</a>
{% endblock content %}

annsusers/templates/annsusers/login.html
{% extends "annslogsapp/base.html" %}
{% load bootstrap3 %}
{% block header %}
    <h2>Log in to your account.</h2>
{% endblock header %}
{% block content %}
    {% if form.errors %}
        <p>Your username and password didn't match. Please try again.</p>
    {% endif %}
        <form method="post" action="{% url 'annsusers:login' %}" class="form">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
            <button name="submit" class="btn btn-primary">Log in</button>
            {% endbuttons %}
            <input type="hidden" name="next" value="{% url 'annslogsapp:index' %}" />
        </form>
{% endblock content %}

annsusers/templates/annsusers/logout.html
{% extends "annslogsapp/base.html" %}
{% block content %}
    <form method="post" action="{% url 'annsusers:logout' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">Log out</button>
        <input type="hidden" name="next" value="{% url 'annslogsapp:index' %}" />
    </form>
{% endblock content %}

annsusers/templates/annsusers/register.html
{% extends "annslogsapp/base.html" %}
{% load bootstrap3 %}
{% block header %}
    <h2>Register an account.</h2>
{% endblock header %}

{% block content %}
    <form method="post" action="{% url 'annsusers:register' %}" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
        <button name="submit" class="btn btn-primary">Register</button>
        {% endbuttons %}
        <input type="hidden" name="next" value="{% url 'annslogsapp:index' %}" />
    </form>
{% endblock content %}